name: Xygeni Full Scan
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Obrigatório para o scanner ler o histórico de commits e autores

      - name: Instalar e executar Xygeni Completo
        run: |
          curl -sSfL https://get.xygeni.io/latest/scanner/get-xygeni.sh | bash
          ~/.xygeni/xygeni scan -n xygeni-goat --dir .
        env:
          XYGENI_URL: https://in.xygeni.io
          XYGENI_TOKEN: ${{ secrets.XYGENI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
